# Build Anders, which both AndersAA and SFS link against.
LEVEL= ../../../../..
LIBRARYNAME= anders
SHARED_LIBRARY= 1
LINK_LIBS_IN_SHARED= 1
#DONT_BUILD_RELINKED= 1
#ENABLE_OPTIMIZED= 1
include $(LEVEL)/Makefile.common
LIBS += -lbdd  #profiler.a 
