# Top-level makefile for the ptr-analysis projects.
CXXFLAGS=-w -fPIC
LEVEL= ../../../..
DIRS= anders anders-aa # sfs-aa
ENABLE_OPTIMIZED= 1
include $(LEVEL)/Makefile.common
#PROJECT_NAME="Pointer Analysis"
#LLVM_SRC_ROOT=../..
#LLVM_OBJ_ROOT=../../build
#PROJ_SRC_ROOT=.
#PROJ_OBJ_ROOT=build
#PROJ_INSTALL_ROOT=/usr/local

include $(LLVM_OBJ_ROOT)/Makefile.config
include $(LLVM_SRC_ROOT)/Makefile.rules

